// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorldBuilder.Models;

[Table("Attribute")]
public partial class Attribute
{
    [Key]
    public int AttIDPK { get; set; }

    [StringLength(100)]
    public string AttName { get; set; }

    public string AttContent { get; set; }

    public bool? AttIsSection { get; set; }
    public int AttOrder { get; set; }

    [InverseProperty("DVAttFKNavigation")]
    public virtual ICollection<DetailView> DetailViews { get; set; } = new List<DetailView>();
}