// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorldBuilder.Models;

[Table("Category")]
public partial class Category
{
    [Key]
    public int CatIDPK { get; set; }

    [Required]
    [StringLength(100)]
    public string CatName { get; set; }

    [StringLength(500)]
    public string CatDescription { get; set; }

    public int? CatWorldFK { get; set; }

    [Required]
    [StringLength(7)]
    public string CatColor { get; set; }

    [ForeignKey("CatWorldFK")]
    [InverseProperty("Categories")]
    public virtual World CatWorldFKNavigation { get; set; }

    [InverseProperty("PicCatFKNavigation")]
    public virtual ICollection<Picture> Pictures { get; set; } = new List<Picture>();

    [InverseProperty("SubCatFKNavigation")]
    public virtual ICollection<SubCategory> SubCategories { get; set; } = new List<SubCategory>();
}