// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorldBuilder.Models;

[Table("ConnectionTable")]
public partial class ConnectionTable
{
    [Key]
    public int ConnIDPK { get; set; }

    [StringLength(50)]
    public string ConnDescr { get; set; }

    public int ConnUserFK { get; set; }

    [InverseProperty("ScriptScriptConnFKNavigation")]
    public virtual ICollection<ScriptScript> ScriptScripts { get; set; } = new List<ScriptScript>();
}