// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorldBuilder.Models;

[PrimaryKey("DVAttFK", "DVScriptFK")]
[Table("DetailView")]
public partial class DetailView
{
    [Key]
    public int DVAttFK { get; set; }

    [Key]
    public int DVScriptFK { get; set; }

    public int? DVPicFK { get; set; }

    [StringLength(100)]
    public string DVTitle { get; set; }

    [ForeignKey("DVAttFK")]
    [InverseProperty("DetailViews")]
    public virtual Attribute DVAttFKNavigation { get; set; }

    [ForeignKey("DVPicFK")]
    [InverseProperty("DetailViews")]
    public virtual Picture DVPicFKNavigation { get; set; }

    [ForeignKey("DVScriptFK")]
    [InverseProperty("DetailViews")]
    public virtual Script DVScriptFKNavigation { get; set; }
}