// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorldBuilder.Models;

[Table("Genre")]
public partial class Genre
{
    [Key]
    [StringLength(100)]
    public string GenreName { get; set; }

    [StringLength(500)]
    public string GenreDescription { get; set; }

    [StringLength(7)]
    public string GenreColor { get; set; }


    [InverseProperty("WorldGenFKNavigation")]
    public virtual ICollection<World> Worlds { get; set; } = new List<World>();
}

// View model for the home-page registry index.
public class GenreViewModel
{
    public string Name { get; set; }
    public string Color { get; set; }
    public List<GenreWorldItem> Worlds { get; set; } = new();
}

// A single world entry inside a genre column — enough to render the row and
// link straight to its detail page.
public class GenreWorldItem
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int Likes { get; set; }
}