// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorldBuilder.Models;

[Table("Genre")]
public partial class Genre
{
    [Key]
    [StringLength(100)]
    public string GenreName { get; set; }

    [StringLength(500)]
    public string GenreDescription { get; set; }

    [StringLength(7)]
    public string GenreColor { get; set; }


    [InverseProperty("WorldGenFKNavigation")]
    public virtual ICollection<World> Worlds { get; set; } = new List<World>();
}

public class GenreViewModel
{
    public string Name { get; set; }
    public List<string> Worlds { get; set; } = new();
}