// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorldBuilder.Models;

[Table("Picture")]
public partial class Picture
{
    [Key]
    public int PicIDPK { get; set; }

    [StringLength(100)]
    public string PicCaption { get; set; }

    [StringLength(400)]
    public string PicPath { get; set; }

    public int? PicSubFK { get; set; }

    public int? PicCatFK { get; set; }

    public int? PicWorldFK { get; set; }

    [InverseProperty("DVPicFKNavigation")]
    public virtual ICollection<DetailView> DetailViews { get; set; } = new List<DetailView>();

    [ForeignKey("PicCatFK")]
    [InverseProperty("Pictures")]
    public virtual Category PicCatFKNavigation { get; set; }

    [ForeignKey("PicSubFK")]
    [InverseProperty("Pictures")]
    public virtual SubCategory PicSubFKNavigation { get; set; }

    [ForeignKey("PicWorldFK")]
    [InverseProperty("Pictures")]
    public virtual World PicWorldFKNavigation { get; set; }

    [ForeignKey("PicScriptPicFK")]
    [InverseProperty("PicScriptPicFKs")]
    public virtual ICollection<Script> PicScriptScriptFKs { get; set; } = new List<Script>();
}