// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorldBuilder.Models;

[PrimaryKey("ScriptScriptOneFK", "ScriptScriptTwoFK")]
[Table("ScriptScript")]
public partial class ScriptScript
{
    [Key]
    public int ScriptScriptOneFK { get; set; }

    [Key]
    public int ScriptScriptTwoFK { get; set; }

    public int ScriptScriptConnFK { get; set; }

    [ForeignKey("ScriptScriptConnFK")]
    [InverseProperty("ScriptScripts")]
    public virtual ConnectionTable ScriptScriptConnFKNavigation { get; set; }

    [ForeignKey("ScriptScriptOneFK")]
    [InverseProperty("ScriptScriptScriptScriptOneFKNavigations")]
    public virtual Script ScriptScriptOneFKNavigation { get; set; }

    [ForeignKey("ScriptScriptTwoFK")]
    [InverseProperty("ScriptScriptScriptScriptTwoFKNavigations")]
    public virtual Script ScriptScriptTwoFKNavigation { get; set; }
}