// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorldBuilder.Models;

[Table("Script")]
public partial class Script
{
    [Key]
    public int ScriptIDPK { get; set; }

    public string ScriptContent { get; set; }

    [StringLength(100)]
    public string ScriptTitle { get; set; }

    [StringLength(100)]
    public string ScriptCatFK { get; set; }

    [StringLength(100)]
    public string ScriptSubFK { get; set; }

    [Column(TypeName = "date")]
    public DateTime? ScriptUpdateAt { get; set; }

    [Column(TypeName = "date")]
    public DateTime ScriptCreateAt { get; set; }

    public bool ScriptIsPublic { get; set; }

    public bool ScriptIsChar { get; set; }

    public double? ScriptBoardX { get; set; }

    public double? ScriptBoardY { get; set; }

    [StringLength(7)]
    public string ScriptBoardColor { get; set; }

    [InverseProperty("DVScriptFKNavigation")]
    public virtual ICollection<DetailView> DetailViews { get; set; } = new List<DetailView>();

    [InverseProperty("ScriptLikUserFKNavigation")]
    public virtual ICollection<ScriptLike> ScriptLikes { get; set; } = new List<ScriptLike>();

    [InverseProperty("ScriptScriptOneFKNavigation")]
    public virtual ICollection<ScriptScript> ScriptScriptScriptScriptOneFKNavigations { get; set; } = new List<ScriptScript>();

    [InverseProperty("ScriptScriptTwoFKNavigation")]
    public virtual ICollection<ScriptScript> ScriptScriptScriptScriptTwoFKNavigations { get; set; } = new List<ScriptScript>();

    [ForeignKey("PicScriptScriptFK")]
    [InverseProperty("PicScriptScriptFKs")]
    public virtual ICollection<Picture> PicScriptPicFKs { get; set; } = new List<Picture>();

    [ForeignKey("ScriptTagScriptFK")]
    [InverseProperty("ScriptTagScriptFKs")]
    public virtual ICollection<Tag> ScriptTagTagFKs { get; set; } = new List<Tag>();
}