// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorldBuilder.Models;

[PrimaryKey("ScriptLikUserFK", "ScriptLikScriptFK")]
public partial class ScriptLike
{
    [Key]
    public int ScriptLikUserFK { get; set; }

    [Key]
    public int ScriptLikScriptFK { get; set; }

    [ForeignKey("ScriptLikUserFK")]
    [InverseProperty("ScriptLikes")]
    public virtual UserInfo ScriptLikUserFK1 { get; set; }

    [ForeignKey("ScriptLikUserFK")]
    [InverseProperty("ScriptLikes")]
    public virtual Script ScriptLikUserFKNavigation { get; set; }
}