// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorldBuilder.Models;

[Table("SubCategory")]
public partial class SubCategory
{
    [Key]
    public int SubIDPK { get; set; }

    [Required]
    [StringLength(100)]
    public string SubName { get; set; }

    [StringLength(500)]
    public string SubDescription { get; set; }

    public int? SubCatFK { get; set; }

    [InverseProperty("PicSubFKNavigation")]
    public virtual ICollection<Picture> Pictures { get; set; } = new List<Picture>();

    [ForeignKey("SubCatFK")]
    [InverseProperty("SubCategories")]
    public virtual Category SubCatFKNavigation { get; set; }
}