// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorldBuilder.Models;

[Table("Tag")]
public partial class Tag
{
    [Key]
    public int TagIDPK { get; set; }

    [Required]
    [StringLength(100)]
    public string TagName { get; set; }

    [StringLength(200)]
    public string TagDescription { get; set; }

    [StringLength(79)]
    public string TagColor { get; set; }

    public int? TagWorldFK { get; set; }

    public int? TagUserFK { get; set; }

    [ForeignKey("TagUserFK")]
    [InverseProperty("Tags")]
    public virtual UserInfo TagUserFKNavigation { get; set; }

    [ForeignKey("TagWorldFK")]
    [InverseProperty("Tags")]
    public virtual World TagWorldFKNavigation { get; set; }

    [ForeignKey("ScriptTagTagFK")]
    [InverseProperty("ScriptTagTagFKs")]
    public virtual ICollection<Script> ScriptTagScriptFKs { get; set; } = new List<Script>();
}