// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WorldBuilder.Models;

[Table("UserInfo")]
public partial class UserInfo
{
    [Key]
    public int UserInfoIDPK { get; set; }

    [Required]
    [StringLength(450)]
    public string UserInfoUserIDFK { get; set; }

    [StringLength(500)]
    public string UserInfoBio { get; set; }

    [StringLength(10)]
    public string UserInfoProN { get; set; }

    [Column(TypeName = "date")]
    public DateTime UserInfoCreatedAt { get; set; }

    [InverseProperty("ScriptLikUserFK1")]
    public virtual ICollection<ScriptLike> ScriptLikes { get; set; } = new List<ScriptLike>();

    [InverseProperty("TagUserFKNavigation")]
    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();

    [InverseProperty("WorldUserFKNavigation")]
    public virtual ICollection<World> Worlds { get; set; } = new List<World>();

    [ForeignKey("WorldLikUserFK")]
    [InverseProperty("WorldLikUserFKs")]
    public virtual ICollection<World> WorldLikWorldFKs { get; set; } = new List<World>();
}