// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WorldBuilder.Models;

[Table("World")]
public partial class World
{
    [Key]
    public int WorldIDPK { get; set; }

    [StringLength(100)]
    public string WorldName { get; set; }

    [StringLength(500)]
    public string WorldDesc { get; set; }

    [Required]
    [StringLength(100)]
    public string WorldGenFK { get; set; }

    public bool WorldIsPublic { get; set; }

    public int WorldUserFK { get; set; }

    [Column(TypeName = "date")]
    public DateTime WorldCreatedAt { get; set; }

    [Column(TypeName = "date")]
    public DateTime? WorldUpdatedAt { get; set; }

    public int? WorldLikes { get; set; }

    [InverseProperty("CatWorldFKNavigation")]
    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();

    [InverseProperty("PicWorldFKNavigation")]
    public virtual ICollection<Picture> Pictures { get; set; } = new List<Picture>();

    [InverseProperty("TagWorldFKNavigation")]
    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();

    [ForeignKey("WorldGenFK")]
    [InverseProperty("Worlds")]
    public virtual Genre WorldGenFKNavigation { get; set; }

    [ForeignKey("WorldUserFK")]
    [InverseProperty("Worlds")]
    public virtual UserInfo WorldUserFKNavigation { get; set; }

    [ForeignKey("WorldLikWorldFK")]
    [InverseProperty("WorldLikWorldFKs")]
    public virtual ICollection<UserInfo> WorldLikUserFKs { get; set; } = new List<UserInfo>();
}