// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WorldBuilder.Models;

public partial class WorldBuilderDBContext : DbContext
{
    //public WorldBuilderDBContext()
    //{
    //}

    public WorldBuilderDBContext(DbContextOptions<WorldBuilderDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Attribute> Attributes { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<ConnectionTable> ConnectionTables { get; set; }

    public virtual DbSet<DetailView> DetailViews { get; set; }

    public virtual DbSet<Genre> Genres { get; set; }

    public virtual DbSet<Picture> Pictures { get; set; }

    public virtual DbSet<Script> Scripts { get; set; }

    public virtual DbSet<ScriptLike> ScriptLikes { get; set; }

    public virtual DbSet<ScriptScript> ScriptScripts { get; set; }

    public virtual DbSet<SubCategory> SubCategories { get; set; }

    public virtual DbSet<Tag> Tags { get; set; }

    public virtual DbSet<UserInfo> UserInfos { get; set; }

    public virtual DbSet<World> Worlds { get; set; }
    public virtual DbSet<GenreRequest> GenreRequests { get; set; }

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=clarification-wriggly.with.playit.plus,1044;Initial Catalog=WorldBuilderDB;Persist Security Info=True;User ID=Princess;Password=0105;Encrypt=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasOne(d => d.CatWorldFKNavigation).WithMany(p => p.Categories).HasConstraintName("FK_Category_World");
        });

        modelBuilder.Entity<ConnectionTable>(entity =>
        {
            entity.HasKey(e => e.ConnIDPK).HasName("PK_Connection");
        });

        modelBuilder.Entity<DetailView>(entity =>
        {
            entity.HasOne(d => d.DVAttFKNavigation).WithMany(p => p.DetailViews)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DetailView_Attribute");

            entity.HasOne(d => d.DVPicFKNavigation).WithMany(p => p.DetailViews).HasConstraintName("FK_DetailView_Picture");

            entity.HasOne(d => d.DVScriptFKNavigation).WithMany(p => p.DetailViews)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DetailView_Script");
        });

        modelBuilder.Entity<Picture>(entity =>
        {
            entity.HasOne(d => d.PicCatFKNavigation).WithMany(p => p.Pictures).HasConstraintName("FK_Picture_Category");

            entity.HasOne(d => d.PicSubFKNavigation).WithMany(p => p.Pictures).HasConstraintName("FK_Picture_SubCategory");

            entity.HasOne(d => d.PicWorldFKNavigation).WithMany(p => p.Pictures).HasConstraintName("FK_Picture_World");

            entity.HasMany(d => d.PicScriptScriptFKs).WithMany(p => p.PicScriptPicFKs)
                .UsingEntity<Dictionary<string, object>>(
                    "PictureScript",
                    r => r.HasOne<Script>().WithMany()
                        .HasForeignKey("PicScriptScriptFK")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_PictureScript_Script"),
                    l => l.HasOne<Picture>().WithMany()
                        .HasForeignKey("PicScriptPicFK")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_PictureScript_Picture"),
                    j =>
                    {
                        j.HasKey("PicScriptPicFK", "PicScriptScriptFK");
                        j.ToTable("PictureScript");
                    });
        });

        modelBuilder.Entity<Script>(entity =>
        {
            entity.HasMany(d => d.ScriptTagTagFKs).WithMany(p => p.ScriptTagScriptFKs)
                .UsingEntity<Dictionary<string, object>>(
                    "ScriptTag",
                    r => r.HasOne<Tag>().WithMany()
                        .HasForeignKey("ScriptTagTagFK")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_ScriptTag_Tag"),
                    l => l.HasOne<Script>().WithMany()
                        .HasForeignKey("ScriptTagScriptFK")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_ScriptTag_Script"),
                    j =>
                    {
                        j.HasKey("ScriptTagScriptFK", "ScriptTagTagFK");
                        j.ToTable("ScriptTag");
                    });
        });

        modelBuilder.Entity<ScriptLike>(entity =>
        {
            entity.HasOne(d => d.ScriptLikUserFKNavigation).WithMany(p => p.ScriptLikes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ScriptLikes_Script");

            entity.HasOne(d => d.ScriptLikUserFK1).WithMany(p => p.ScriptLikes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ScriptLikes_UserInfo");
        });

        modelBuilder.Entity<ScriptScript>(entity =>
        {
            entity.HasKey(e => new { e.ScriptScriptOneFK, e.ScriptScriptTwoFK }).HasName("PK_SciptScipt");

            entity.HasOne(d => d.ScriptScriptConnFKNavigation).WithMany(p => p.ScriptScripts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SciptScipt_ConnectionTable");

            entity.HasOne(d => d.ScriptScriptOneFKNavigation).WithMany(p => p.ScriptScriptScriptScriptOneFKNavigations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SciptScipt_Script");

            entity.HasOne(d => d.ScriptScriptTwoFKNavigation).WithMany(p => p.ScriptScriptScriptScriptTwoFKNavigations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SciptScipt_Script1");
        });

        modelBuilder.Entity<SubCategory>(entity =>
        {
            entity.HasOne(d => d.SubCatFKNavigation).WithMany(p => p.SubCategories).HasConstraintName("FK_SubCategory_Category");
        });

        modelBuilder.Entity<Tag>(entity =>
        {
            entity.HasOne(d => d.TagUserFKNavigation).WithMany(p => p.Tags).HasConstraintName("FK_Tag_UserInfo");

            entity.HasOne(d => d.TagWorldFKNavigation).WithMany(p => p.Tags).HasConstraintName("FK_Tag_World");
        });

        modelBuilder.Entity<UserInfo>(entity =>
        {
            entity.HasMany(d => d.WorldLikWorldFKs).WithMany(p => p.WorldLikUserFKs)
                .UsingEntity<Dictionary<string, object>>(
                    "WorldLike",
                    r => r.HasOne<World>().WithMany()
                        .HasForeignKey("WorldLikWorldFK")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_WorldLikes_World"),
                    l => l.HasOne<UserInfo>().WithMany()
                        .HasForeignKey("WorldLikUserFK")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_WorldLikes_UserInfo"),
                    j =>
                    {
                        j.HasKey("WorldLikUserFK", "WorldLikWorldFK");
                        j.ToTable("WorldLikes");
                    });
        });

        modelBuilder.Entity<World>(entity =>
        {
            entity.HasOne(d => d.WorldGenFKNavigation).WithMany(p => p.Worlds)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_World_Genre");

            entity.HasOne(d => d.WorldUserFKNavigation).WithMany(p => p.Worlds)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_World_UserInfo");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}